### ISSUE TITLE
The FT sensor are not currently exported

### ISSUE THREAD

**Issue by iron76** [kzts/athletebot#3]
The current sdf model (generated with https://github.com/robotology/simmechanics-to-urdf) does not embed properly the FT sensors. The .stl file is embedded but in order to simulate them a proper `force_torque` sensor and `gazebo_yarp_forcetorque` plugin should be embedded in the sdf. @traversaro: should this be performed manually or automatically?

**Comment by traversaro** [comment]
They should be generated automatically using `simmechanics-to-urdf`, see https://github.com/robotology/simmechanics-to-urdf#forcetorque-sensors-parameters-keys-of-elements-of-forcetorquesensors and  https://github.com/robotology/simmechanics-to-urdf/blob/master/test/legs_simmechanics_options.yaml#L104

**Comment by traversaro** [comment]
Notice that due to URDF limitations the frame of the FT sensor will be the one fixed joint at which it is attached, and so the one of the **child** link. For this reason in the iCubHeidelberg01 model I assign the frames of the child link of the ft sensors to some user specified frame : https://github.com/robotology/simmechanics-to-urdf/blob/master/test/legs_simmechanics_options.yaml#L90 .

**Comment by iron76** [comment]
@kzts and @nskw this needs to be fixed since FT sensors are the one used to compute joint torques, internal whole-body dynamics and external forces. They are necessary to test the wholeBodyDynamicsTree (http://wiki.icub.org/codyco/dox/html/group__wholeBodyDynamicsTree.html) at first and the wholeBodyInterface later on (https://github.com/robotology/yarp-wholebodyinterface).

**Comment by nskw** [comment]
I tried to set frames for FT sensors as the following. 

```
linkFrames: 
  - linkName: l_hip_ftsens
    frameName: SCSYS_FT45
    frameReferenceLink: l_hip_in_up
  - linkName: r_hip_ftsens
    frameName: SCSYS_FT45
    frameReferenceLink: r_hip_in_up
  - linkName: l_foot_ftsens
    frameName: SCSYS_FT45
    frameReferenceLink: l_foot
  - linkName: r_foot_ftsens
    frameName: SCSYS_FT45
    frameReferenceLink: r_foot
```

But, I got the following error message. 

```
Traceback (most recent call last):
  File "/usr/local/bin/simmechanics_to_urdf", line 9, in <module>
    load_entry_point('simmechanics-to-urdf==0.2', 'console_scripts', 'simmechanics_to_urdf')()
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 1524, in main
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 150, in convert
  File "build/bdist.linux-x86_64/egg/simmechanics_to_urdf/firstgen.py", line 752, in buildTree
KeyError: ('l_foot', 'SCSYS_FT45')
```

**Comment by traversaro** [comment]
Sorry, I just saw that the documentation for the `linkFrames` group was incomplete, I completed it in https://github.com/robotology/simmechanics-to-urdf/commit/50ca6e6f2ffe8d5995bd258fca93661b9021c019 .

The `linkFrames` section does not add a link, but it just assigns a frame to an existing link, so `linkName` should be the name of an existing link.

**Comment by nskw** [comment]
Thank you!
I found that I must reverse `linkName` and `frameReferenceLink`. 
(`linkName` of our  yaml file was already an existing link. `***_ftsens` is CAD part of FT sensor. )

```
linkFrames: 
  - linkName: l_hip_in_up
    frameName: SCSYS_FT45
    frameReferenceLink: l_hip_ftsens
  - linkName: r_hip_in_up
    frameName: SCSYS_FT45
    frameReferenceLink: r_hip_ftsens
  - linkName: l_sole
    frameName: SCSYS_FT45
    frameReferenceLink: l_foot_ftsens
  - linkName: r_sole
    frameName: SCSYS_FT45
    frameReferenceLink: r_foot_ftsens
```
